### PR TITLE
support sbt 1.3.x and later only

### PR DESCRIPTION
**Pull request by bjaglin**
0.10.0 is ahead because of https://github.com/scalacenter/scalafix/pull/1565, so it's a good occasion to clean up!

[sbt 1.3.0](https://github.com/sbt/sbt/releases/tag/v1.3.0) was released more than 2.5 years ago. One reason people on sbt 1.x could still be stuck on sbt 1.2 or earlier could be the introduction of Coursier in 1.3.0, but it can be disabled via `ThisBuild / useCoursier := false`. Therefore I don't think we even need to mention instructions for sbt 1.[0-2] in the docs [like we do for sbt 0.13](https://github.com/scalacenter/scalafix/pull/1417/files#diff-2e28f911279567cbb268785581f61db7f687f49d4adedbd85a06b0943fbcd320) (for which the migration path is arguably harder).

sbt-scalafix has been very conservative so far, but I think it's time to remove complexity from the implementation and the [docs](https://github.com/scalacenter/scalafix/pull/1572). Building against sbt 1.3.x also opens the door for leveraging https://www.scala-sbt.org/1.x/docs/Howto-Track-File-Inputs-and-Outputs.html#Incremental+builds and hopefully simplifying [the code providing incremental runs](https://github.com/scalacenter/sbt-scalafix/blob/fc9b70f76eb638c104da36770f9ea710246b3534/src/main/scala/scalafix/sbt/ScalafixPlugin.scala#L559-L623).

Loading this with sbt <1.3 fails hard as expected (like many other sbt plugins do actually)
```
➜ cat project/plugins.sbt    
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.34+24-fb6dcd83-SNAPSHOT")
resolvers += Resolver.sonatypeRepo("snapshots")
➜ sbt --sbt-version 1.2.8    
[info] Updated file /tmp/sbt/project/build.properties: set sbt.version to 1.2.8
[info] Loading global plugins from /home/brice/.sbt/1.0/plugins
[info] Compiling 1 Scala source to /home/brice/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes ...
[info] Done compiling.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/brice/.sbt/boot/scala-2.12.7/org.scala-sbt/sbt/1.2.8/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] Loading project definition from /tmp/sbt/project/project
[info] Loading settings for project sbt-build from plugins.sbt ...
[info] Loading project definition from /tmp/sbt/project
[error] java.lang.NoSuchMethodError: 'sjsonnew.JsonFormat sbt.package$.singleFileJsonFormatter()'
[error] 	at scalafix.sbt.ScalafixPlugin$autoImport$.<init>(ScalafixPlugin.scala:127)
...
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: 'sjsonnew.JsonFormat sbt.package$.singleFileJsonFormatter()'
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? %    
```

### CODE REVIEW

File: build.sbt [hunk 1]
```diff
@@ -48,14 +48,11 @@ libraryDependencies ++= List(
 scalaVersion := "2.12.15"
 
 // keep this as low as possible to avoid running into binary incompatibility such as https://github.com/sbt/sbt/issues/5049
-// check if following hacks can be removed upon bumping:
-// - SemanticdbPlugin
-// - includePluginResolvers
-pluginCrossBuild / sbtVersion := "1.2.1"
+pluginCrossBuild / sbtVersion := "1.3.4"
```
Comment (bjaglin) [inline build.sbt:51]: `scalafixEnable` has never reliably worked on sbt 1.3.[0-3] as `semanticdbVersion` as setting it at the project level had no effect until https://github.com/sbt/sbt/pull/5202 (backported in 1.3.4).

File: build.sbt [hunk 2]
```diff
@@ -48,14 +48,11 @@ libraryDependencies ++= List(
 scalaVersion := "2.12.15"
 
 // keep this as low as possible to avoid running into binary incompatibility such as https://github.com/sbt/sbt/issues/5049
-// check if following hacks can be removed upon bumping:
-// - SemanticdbPlugin
-// - includePluginResolvers
-pluginCrossBuild / sbtVersion := "1.2.1"
+pluginCrossBuild / sbtVersion := "1.3.1"
```
Comment (bjaglin) [inline build.sbt:51]: it's a bit strange to have this higher than the scripted version, see commit message

File: src/main/scala/scalafix/sbt/ScalafixEnable.scala [hunk 3]
```diff
@@ -61,73 +55,14 @@ object ScalafixEnable {
...
-        )
-      } :+ (SemanticdbPlugin.semanticdbEnabled := true)
+      enableSemanticdbPlugin <- maybeFullVersion.toList.map { fullVersion =>
+        scalaVersion := fullVersion,
+      } :+ (semanticdbEnabled := true)
       settings <-
         inScope(ThisScope.copy(project = Select(p)))(
           scalacOptionsSettings ++ enableSemanticdbPlugin
-        )
+        ) :+ (Global / semanticdbVersion := BuildInfo.scalametaVersion)
```
Comment (bjaglin) [inline src/main/scala/scalafix/sbt/ScalafixEnable.scala:64]: As explained in the commit, this makes `scalafixEnable` work properly on sbt 1.3.[0-3]. This is also broken on master since https://github.com/scalacenter/sbt-scalafix/commit/5e14eb5f4471f960954050454fda54bac0b11d62, but using 1.3.0 for scripted tests exposed this.

**Comment by bjaglin** [comment]
cc @olafurpg

**Comment by olafurpg** [comment]
LGTM

**Review by mlachkar — APPROVED** [review]
